export const TableDataActionTypes = {
  SET_CURRENT_TABLE: "SET_CURRENT_TABLE",
  SET_AUTHOR_NAME: "SET_AUTHOR_NAME",
  SET_PERCENTAGE: "SET_PERCENTAGE",
  SET_START_DATE: "SET_START_DATE",
  SET_END_DATE: "SET_END_DATE",
};
