export const ProductActionTypes = {
  SET_SELECTED_PRODUCTS: "SET_SELECTED_PRODUCTS",
  ADD_ITEM: "ADD_ITEM",
  CLEAR_ITEM: "CLEAR_ITEM",
  FETCH_PRODUCTS_START: "FETCH_PRODUCTS_START",
  FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
  FETCH_PRODUCTS_FAILURE: "FETCH_PRODUCTS_FAILURE",
};
